server:
  port: 8083

spring:
  application:
    name: ride-management-service-test
  data:
    mongodb:
      uri: ${RIDE_MONGODB_URI:mongodb+srv://it24102971_db_user:4Yz9waUXesMwrAlz@ridelink.pcs3g0k.mongodb.net/ridelink_ride_db?retryWrites=true&w=majority}
      database: ridelink_ride_db
      auto-index-creation: false

services:
  account:
    url: http://localhost:8081
    connect-timeout-ms: 1000
    read-timeout-ms: 1000
  driver:
    url: http://localhost:8082
    connect-timeout-ms: 1000
    read-timeout-ms: 1000

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    root: WARN
    com.ridelink.ridemanagement: INFO
